---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-registry-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBB7jOvZq6HrvBrT+YDYXtxHnKeeHui0mDLpBJjIPGKhThHDQ//ix3zTDA1rK9la5mNfu9cNwLW0dvzZozh1G94Qp9APn3BbAwOyFU7Q74DPLzNLAfLyUWnZ9GDfI9u3OBkv0Ck/Zg+n1vrfBv60Z9ZxqIVwjw97tg2mP/QZCl8Zv844CAM0f5JSwPTe28M0SbLK40m/RpSl810/s1qKPFSGj+bpY7FQts/D8h7tBVBG3f+IwfLqtWUceisre3LewEAtDZ04SA8wbGhc64uCntdIJJJ1ioeg7y9vxaYVaWO1Hx3ZK9gHfRkiAsfxRFcjEyLIRGJctWYR987LQQr2rlB8VbgVJLllRLzJ8AGbHcavsNEzbVlELwSWaNUFtF76awWOMqyq8chtd39qf+kU85srJoY4ec83K2tBu4eKiNvm6Qq78qPU7weq9i2oNpqVApRZUUZJAPqMEyxOBxTLHKT44jpLBnpjB6Uuu4hU4TI02Z3FtqnJORsr2SPQ3G+YZH2fxGbuxb0+mFCQM7NDEO35bRLAZZkLDqWkDw1DV58T/k37FEdhzLxylZdKPoAJmdG/4yn7GL7wXON6l3cOdP2tSGXBxjjlhm3SfTwy2vtS6mbPYcr2dLRzLeq8ZVNtIWoMuz6sB1Sug3E+hgHm+/dtbwUBto1nSmBu3y9mYrRU9FvBDEzCNF7AgB0+s+PDzXnym8yia6OOWMmBm4HRZLj9SC9m28QvHLPZKX2NM11mCkDwAczv0SilZDML9jWXxJc53KAnWd2BJPYFa2csWHaBcAItrmGnJmvl6ZrMGid9VTUqdllA8bloej8ppJklvo2l+w6SdYxNHfIwatkR2qkBeHfGMlxMRPFRsu9sXIACJq1TjY1DPssAWWHnkS0iQffSHVFmD8oB/J2pgsRKx9n8mVIh3pl3xTRnUnp5wFcm/uoDWt+q+1qlUIYUx9q+rc=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-registry-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
