apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-chat-data-pvc
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi